name: automated_deploy_to_ec2

on:
  push:
    branches:
      - 'main'

env:
  SERVICE_NAME: online_education_app_node

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Create and populate .env file for node.js
        run: |
          cat <<EOF > .env
          # DB Config
          DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          # AWS S3 Config
          S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_BUCKET=${{ secrets.S3_BUCKET }}
          S3_REGION=${{ secrets.S3_REGION }}
          EOF
          cat .env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.SERVICE_NAME}}:latest
      -
        name: Pull and Run on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{env.SERVICE_NAME}}:latest
            docker stop ${{env.SERVICE_NAME}}
            docker rm ${{env.SERVICE_NAME}}
            docker run -d --name ${{env.SERVICE_NAME}} -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/${{env.SERVICE_NAME}}:latest